inherit_gem:
  rubocop-lazy-config: rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    # https://github.com/glebm/i18n-tasks#installation
    - test/i18n_test.rb

# @user = User.find_by_password_reset_token!(params[:token])
Rails/DynamicFindBy:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 80

Minitest/MultipleAssertions:
  Max: 12

Lint/AssignmentInCondition:
  Enabled: false

Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
