inherit_gem:
  rubocop-lazy-config: rubocop.yml

# @user = User.find_by_password_reset_token!(params[:token])
Rails/DynamicFindBy:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 80

Minitest/MultipleAssertions:
  Max: 10
